# Generated by Django 5.2 on 2025-05-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='professional_photo',
            field=models.ImageField(blank=True, help_text='Foto profesional que aparecerá junto al nombre en la sección principal.', null=True, upload_to='profile/professional/'),
        ),
    ]
