# Generated by Django 5.2 on 2025-05-12 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_profile_professional_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='certification',
            name='institution_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Institution (English)'),
        ),
        migrations.AddField(
            model_name='certification',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (English)'),
        ),
        migrations.AddField(
            model_name='education',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='education',
            name='institution_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Institution (English)'),
        ),
        migrations.AddField(
            model_name='education',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (English)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio_en',
            field=models.TextField(blank=True, null=True, verbose_name='Biography (English)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (English)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Professional Title (English)'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Technologies (English)'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (English)'),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (English)'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption (English)'),
        ),
        migrations.AddField(
            model_name='projectvideo',
            name='caption_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption (English)'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Archivo de certificado'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='date_obtained',
            field=models.DateField(verbose_name='Fecha de obtención'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de expiración'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='institution',
            field=models.CharField(max_length=255, verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('phone', 'Phone'), ('email', 'Email')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduation_year',
            field=models.IntegerField(verbose_name='Año de graduación'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=255, verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='education',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='education',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to='profile/', verbose_name='Foto principal'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='professional_photo',
            field=models.ImageField(blank=True, help_text='Foto profesional que aparecerá junto al nombre en la sección principal.', null=True, upload_to='profile/professional/', verbose_name='Foto profesional'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título profesional'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de GitHub'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL del proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(max_length=255, verbose_name='Tecnologías'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(upload_to='projects/', verbose_name='Imagen miniatura'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='document',
            field=models.FileField(upload_to='projects/documents/', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='portfolio.project', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Pie de foto'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='projects/images/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='projectvideo',
            name='caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Pie de video'),
        ),
        migrations.AlterField(
            model_name='projectvideo',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='projectvideo',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='portfolio.project', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='projectvideo',
            name='video',
            field=models.FileField(upload_to='projects/videos/', verbose_name='Video'),
        ),
    ]
