# Generated by Django 5.2 on 2025-05-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_certification_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('phone', 'Phone'), ('email', 'Email')], max_length=20, verbose_name='Tipo'),
        ),
    ]
