# Generated by Django 5.2 on 2025-05-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='project',
            name='company_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company (English)'),
        ),
        migrations.AddField(
            model_name='project',
            name='current_job',
            field=models.BooleanField(default=False, verbose_name='Trabajo actual'),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='project',
            name='position_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Position (English)'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('project', 'Proyecto'), ('work', 'Experiencia Laboral')], default='project', max_length=10, verbose_name='Tipo'),
        ),
    ]
