# Generated by Django 5.2 on 2025-05-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_project_company_project_company_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('book', 'Libro'), ('article', 'Artículo Científico'), ('conference', 'Conferencia'), ('thesis', 'Tesis'), ('other', 'Otro')], default='article', max_length=15, verbose_name='Tipo de Publicación')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('authors', models.CharField(max_length=255, verbose_name='Autores')),
                ('journal_or_publisher', models.CharField(max_length=255, verbose_name='Revista/Editorial')),
                ('abstract', models.TextField(verbose_name='Resumen')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (English)')),
                ('authors_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Authors (English)')),
                ('journal_or_publisher_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Journal/Publisher (English)')),
                ('abstract_en', models.TextField(blank=True, null=True, verbose_name='Abstract (English)')),
                ('publication_date', models.DateField(verbose_name='Fecha de publicación')),
                ('doi', models.CharField(blank=True, max_length=100, null=True, verbose_name='DOI')),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL de la publicación')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='publications/', verbose_name='Archivo PDF')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='publications/', verbose_name='Imagen de portada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['order', '-publication_date'],
            },
        ),
    ]
