# Generated by Django 5.2 on 2025-05-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='credential_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de la credencial'),
        ),
    ]
