# Generated by Django 5.2 on 2025-05-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_skill_project_company_logo_project_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='skills',
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Habilidades (separadas por comas)'),
        ),
    ]
