# Generated by Django 5.2 on 2025-05-13 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_project_category_remove_project_skills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, verbose_name='Empresa')),
                ('position', models.CharField(max_length=255, verbose_name='Cargo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('company_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company (English)')),
                ('position_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Position (English)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description (English)')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='companies/', verbose_name='Logo de la empresa')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('current_job', models.BooleanField(default=False, verbose_name='Trabajo actual')),
                ('skills', models.CharField(blank=True, max_length=255, null=True, verbose_name='Habilidades (separadas por comas)')),
                ('technologies', models.CharField(max_length=255, verbose_name='Tecnologías')),
                ('technologies_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Technologies (English)')),
                ('thumbnail', models.ImageField(upload_to='work/', verbose_name='Imagen miniatura')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Experiencia Laboral',
                'verbose_name_plural': 'Experiencias Laborales',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='company',
        ),
        migrations.RemoveField(
            model_name='project',
            name='company_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='project',
            name='current_job',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='position',
        ),
        migrations.RemoveField(
            model_name='project',
            name='position_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('project', 'Proyecto')], default='project', max_length=10, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='WorkExperienceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='work/documents/', verbose_name='Documento')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (English)')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('work_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='portfolio.workexperience', verbose_name='Experiencia Laboral')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperienceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work/images/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Pie de foto')),
                ('caption_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption (English)')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('work_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.workexperience', verbose_name='Experiencia Laboral')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
