# Generated by Django 5.2 on 2025-05-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_workexperience_remove_project_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='technologies',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='technologies_en',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Palabras clave/Funciones desempeñadas'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='keywords_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords/Functions (English)'),
        ),
    ]
