# Generated by Django 5.2 on 2025-05-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_remove_workexperience_technologies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.CharField(blank=True, help_text='Selecciona las habilidades en el formulario de edición', max_length=255, null=True, verbose_name='Habilidades'),
        ),
    ]
